### ISSUE TITLE
miniPandAに課題画表示されない

### ISSUE THREAD

**Issue by 1taroh** [comfortable-panda/ComfortablePandA-Extension#8]
以前までは表示されていたPandA上の課題が表示されなくなったので，表示できるようにしてほしいです．
タブの再読み込みや再ログインをしても変わらず課題の表示はされませんでした．

Comfortable PandA 3.0
google chrome 89.0.4389.128
<img width="956" alt="2021-04-14" src="https://user-images.githubusercontent.com/65810214/114630898-83ad6980-9cf6-11eb-85d7-df5402098c5e.png">

**Comment by 1taroh** [comment]
なぜか治ってました...

**Comment by das08** [comment]
ご報告ありがとうございました
